# Generated by Django 4.1.2 on 2022-11-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapi', '0002_company_employee_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company_id',
            new_name='company',
        ),
    ]
